version: '3.9'

services:
  postgres:
      container_name: agenda_ai_postgres
      image: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=agenda_ai