server:
  port: 8087
  servlet:
    context-path: '/agendaai-authuser/'

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/agendaai-authuser
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.postgresql.Driver
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
